#!/bin/bash
##############################
#
# Halloween 2015
# presence@irev.net
#
##############################

usage() {
	echo "Halloween Modes"
	echo "Usage:"
	echo "\t h nice"
	echo "\t h scary"
}

if [ -n "$1" ]; then
	while [ "$1" != "" ]; do
		for i in {1..100}
		do
			case $1 in
				nice)
					treeright=$((100+RANDOM % 100));
					treeleft=$((50+RANDOM % 50));
					cordpurp=255;
					lampfar=$((100+RANDOM % 100));
					lampnear=$((100+RANDOM % 100));
					doororange=255;
					doorpurp=0;
					treepurp=$((200+RANDOM % 50));
					mayhem=70; # blue
					### Garage Door Wash DMX 21
					r1=255;
					g1=$((100+RANDOM % 100));
					b1=$((50+RANDOM % 50));
					### Alcove Light 30
					r2=255;
					g2=100;
					b2=0;
					### Far Wall Uplight 40
					r3=$((50+RANDOM % 50));
					g3=$((100+RANDOM % 100));
					b3=0;
					### Close Wall Uplight 50
					r4=$((50+RANDOM % 50));
					g4=$((100+RANDOM % 100));
					b4=0;
					/usr/local/bin/ola_streaming_client -u 1 -d \
					$treeright,$treeleft,$cordpurp,$lampfar,$doorpurp,$doororange,$treepurp,$lampnear,$mayhem,0,0,0,0,0,0,0,0,0,0,0,$r1,$g1,$b1,0,0,0,0,0,0,$r2,$g2,$b2,0,0,0,0,0,0,0,$r3,$g3,$b3,0,0,0,0,0,0,0,$r4,$g4,$b4,0,0,0,0
					;;
				scary)
					treeright=$((50+RANDOM % 50));
					treeleft=$((10+RANDOM % 50));
					cordpurp=$((100+RANDOM % 150));
					lampfar=$((50+RANDOM % 50));
					lampnear=$((50+RANDOM % 50));
					doororange=0;
					doorpurp=255;
					treepurp=$((100+RANDOM % 150));
					mayhem=110; # redblue
					### Garage Door Wash DMX 21
					r1=0;
					g1=100;
					b1=$((100+RANDOM % 50));
					### Alcove Light 30
					r2=0;
					g2=0;
					b2=255;
					### Far Wall Uplight 40
					r3=0;
					g3=0;
					b3=255;
					### Close Wall Uplight 50
					r4=0;
					g4=0;
					b4=255;
					/usr/local/bin/ola_streaming_client -u 1 -d \
					$treeright,$treeleft,$cordpurp,$lampfar,$doorpurp,$doororange,$treepurp,$lampnear,$mayhem,0,0,0,0,0,0,0,0,0,0,0,$r1,$g1,$b1,0,0,0,0,0,0,$r2,$g2,$b2,0,0,0,0,0,0,0,$r3,$g3,$b3,0,0,0,0,0,0,0,$r4,$g4,$b4,0,0,0,0
					;;
				*)
					usage
					exit 1
					;;
				esac
			done
			shift
		done
	else
		usage
		exit 1
fi
